### PR TITLE
Feature/beagle orange

### PR DESCRIPTION
**Pull request by Tiagoperes**
# Description
This pull request brings all the work from the team `Orange - UX Services - Beagle Open Core` to the Beagle Open Source project.

Tasks for merging this into the main branch:
- [x] Merge the main into this discarding the changes made to expose the rootId in the analytics (the code base is way too different now, it's easier to re-implement).
- [x] Reimplement the rootId on analytics feature
- [x] Decide what to do with the "signed commits" check. There are two options: (1) remove the information of who committed what and make a signed commit of everything at once. (2) disable this check for this PR. I prefer the second so we can keep each commit information, but this decision is up to the open source team.
- [x] Have both Beagle Android and Beagle React versions of this ready to be merged.

# Related PRs
- [React](https://github.com/ZupIT/beagle-web-react/pull/248)
- [Angular](https://github.com/ZupIT/beagle-web-angular/pull/317)
- [Flutter](https://github.com/ZupIT/beagle-flutter/pull/44)
- [Android](https://github.com/ZupIT/beagle-android/pull/70)
- [iOS](https://github.com/ZupIT/beagle-ios/pull/301)
- [Backend Kotlin](https://github.com/ZupIT/beagle-backend-kotlin/pull/62)
- [Tests](https://github.com/ZupIT/beagle-tests/pull/28)
- [Docs](https://github.com/ZupIT/beagle-docs/pull/837)

### CODE REVIEW

**Comment by lucasfonsecazup** [comment]
```Decide what to do with the "signed commits" check. There are two options: (1) remove the information of who committed what and make a signed commit of everything at once. (2) disable this check for this PR. I prefer the second so we can keep each commit information, but this decision is up to the open source team.
```

We decided to disable this check for this PR since they are optional options.

**Comment by hectorcustodiozup** [comment]
For now we can ignore the checks for DCO as keeping the authors and history seems to be the best solution indeed.

**Comment by Tiagoperes** [comment]
We've probably removed things like DCO validation. To fix this, just copy the current version at the main branch.

**Comment by Tiagoperes** [comment]
As for me, this can be merged into the main repo.

This is currently being blocked for 2 reasons:
- DCO: we agreed to ignore this.
- Headers: it's complaining about 2 files. These are false positives, the headers are all correct.

I'm just waiting for @hectorcustodiozup approval to merge this.

**Review by hectorcustodiozup — DISMISSED** [review]

**Review by hectorcustodiozup — APPROVED** [review]
Sorry for taking the delay @Tiagoperes, the PR took me longer to analyze than expected. The Header was a diference of quote marks from simple ' to double ", The snapshots I ignored as they are generated and there is no need for header in them.

DCO can be ignored for this PR.

**Pull request merged**
